travis:
  secure:
    BINSTAR_TOKEN: WQvq6/1SRa6/rO+r9kjcab3ulPEuUIcz7qgZoN1z8YCfRMoz9NxY7NpUg8fN+VH/9W7fcr3Rm0h0Fzo6yYqjwth0RyiFOqV8IiTV+RBU6B8dD91KEPxTwXoFTh4UbEXxnBAvLXGgRCDMnqgl+5eaNIL6TczFDssGIEQU876EnoLCmRYHj5MKFYMoqIsVuGp1gnyJgHdL78ql86uAS6Ok/oLGZl7/Wx27sI4XgdKRirYKY7oMgyS4mLjEsCuM1x+NN5VTtVhjc8cH40zb4n7Psxrwz2xzLpjYoncPgPABGCck51SWS9t0N+QeOBp51eAnB9aV1hUn/8J1UyryCrJvpGyj8nB9dy4xK1w3sQKVUOC8eCZSszIIMFYiOS0rZnBOTbJvPRWNuq4vnuttv/RySlFjpvXb6usZ7F2/l5evzwCRKmXM3FNBteTJnqxSfaPG6itQwoM8GXR8wHOZITQLVSe6y84P0DGUqrZhQmECP9rvjysr1ZbGRDkf4NX0aRop9yx7W7paFodoLJZ4rp8nBYhxIpAfIHtsdl87mLLIXlmpSdDQfYNDTG76Iia4xKj+8lIeJKthfEqgV/M7CesExLyslrcQE1cqaZZiWprlTJvg5pGeHRHZlw+li2mGNrXWtVojItG4TcZoLcVJrItYJ/OHmlTDyltFZs8V9z14C3k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
