travis:
  secure:
    BINSTAR_TOKEN: Ue5PyKN8mIEVlbm0q2YV9mOyHChZga49fKbfJ5yptIj33XwtYbpKaYBedGs3d1q2nJwczU5FPVfix+HNm2OEjc1RmDhdX5fMh5ROFIRZfIJbOZtuquhQkNQMh9OxStwqyppYv9ANh6GgS5Uq2qlCaGreiz4gps4eGkVkp6VLJEtLpDMk1CQGcfrDYjP39RRrI3NoP2BwxTvMdGLSUdNcRVYOqh3pxIBNSErQeXOXhGhO7VfZCtxBOtKyO4uuBFAoZpLzrxAEInk/R0E+NnDUNrAJAY1obSi2JoNVwcv9w87hIg6dYRL+x92KRjQjo31cNZdwl2Ln0XZZDgpjBG4wX5PKtvwc2TIX45um09t9yMg7xuWxSnSMRjP1MAeoj4O/GSfW2n87yaUFpOOvh2iwr1j0kdjmvCTgqJ9z8KJhZgyRnboPax5pFzXcsg8H7tsbiCeHf2O9s1G+VkGVFPPe59C4+A/C6H2FXXAs6EuszUj9YYKg8tQhfGy2DlYoprIrbhND2Ycszi01ww17jPtWPpProsUNfwmt4Sz0FJxoHiBEYRjzWjD8pXKenQwn7JeCPlstd20xtWfIdAWbMI8T8MXbSOl2MUjROQRYXwM1AFVet5gPhHlaJlH52ZLWAUVFqzWKzlsbXab0C1HFjJwxZOtbO22IfXZGISFnYElfTTk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
