travis:
  secure:
    BINSTAR_TOKEN: IOuQ5F0JHLSPPCWDGC0xon/Tv2h3rBcz4LRieC4len421FaSQTBqvESR47FRjdMS3DO4N4R1IxeJ7chS5uuHOh3+tjuNAWHyXLuDXFPFAC2y3IiPfkVi7GBwnHy/8nccPhoPIWnT642ZZB6dy7+1nA3UZrxmbylWjc5cVCSlTp9AP65HvRYmuFQBLfhybQ5qQfdTUtXegq53Mtgwmeldbocm/wlQHbGEo9qodtfwT71+H4vRk+QDN2ucWql520oZDvb3cvL36HJLd7EXwLEkAN40eH7PycUC9daoDiw4FXMzNvC01kxjmxhZathfBc5b5ePoEQp/QMhpK8WYAqeUy6SatyafQV37Go5uV/T3Yqm+QZepQYf3cKQCouqOiqx+eQeQzoVWN5RrszBCR8F+T3+HJuIDcmQY3GSiNWy7u6+5o9+DumLczEIAAP/IYoymhWqPBp6+4/Eg1uSZRimepejmiePo2r+/s7bcGok8fImoQaHLnyF5XqN+Paq7oxEO2HgnQC3SmfT6gqATGDPwBNClxqSICLcBUWcBAq6TR2+wzx/3Y3YFCcKw3F9raYazGFU6MmyQrs8x1z7yGBvlOmgjmBoPrKppYxegzbxVtuiEEIM0B29EFZdd22i2W2hUZjBFfyVJx9EyQx5qxzk0113xr0URy/H3AbgzdicRLng=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
