travis:
  secure:
    BINSTAR_TOKEN: Wt7W+RKXJsOZuHzsVtaSp1fbv3kENI9EV1h44qAdRoLqX3fp7YoEKEtjj+kIjPTY4rd2Gt+/oFvuBMyTbRlVmGbIDRHDpVSAdPVvm72hzOCGQKXhHmI2t8xyeY3qTrvnbPOq5NmuS/FEjNEbS5gMZFjI/pPjXdBbnfzRyhLdsjdLTIr1px/POgZ5SiXaKyh132p33Wmgt+MUdToxyky7nOH1x9REnTv79q6un1b8U1opE+SZLXM30lEdoE+bq/2jYgC3DP3LjoVcvTZwlwwVJYkIuWnTyLzJLdUL1Lrc7DbyItc40BZHJ1aihFKmtuAqdF33HfDFurPpFnZgNoOTF++A42r4u1G1ZOJHWl8kC6GCHZUIUcuhio4CAVJqaB6mjKgAA2rtYI9wiwJ+uvaH4/PVc99GjOCR35qwrGx/6UqTamu8KoqYz/nZyWKxksFIne7C0Qzi2o8j4SknmEdLHT2tTBbAs0iqZ1/psIxLpLPctienH202pDBIH38QBrhJuVeJeIIIPkQ4PFU1HpcmiPJvvE1JOqLEWdfbQrxAbsuZyo57reX8WH4gVrm+ydWNlLeiFnqc67xb1sMJAcFr3DqOY3Y/DU83mb18VP3/QpPESs1ROWXb8cZ9YY8mvBG+Cqvbpl5XgATCKJH6JhXboau3fWxR0C+0IHQ4QY6OTzw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
